export const INDICATORS_FETCH_START = 'INDICATORS_FETCH_START';
export const INDICATORS_FETCH_SUCCESS = 'INDICATORS_FETCH_SUCCESS';
export const INDICATORS_FETCH_FAIL = 'INDICATORS_FETCH_FAIL';
export const INDICATORS_FETCH_END = 'INDICATORS_FETCH_END';
export const SELECT_INDICATOR = 'SELECT_INDICATOR';

export const REGIONS_FETCH_START = 'REGIONS_FETCH_START';
export const REGIONS_FETCH_SUCCESS = 'REGIONS_FETCH_SUCCESS';
export const REGIONS_FETCH_FAIL = 'REGIONS_FETCH_FAIL';
export const REGIONS_FETCH_END = 'REGIONS_FETCH_END';
export const REGIONS_INDICATOR_LOADED = 'REGION_INDICATOR_LOADED';

export const COUNTRIES_FETCH_START = 'COUNTRIES_FETCH_START';
export const COUNTRIES_FETCH_SUCCESS = 'COUNTRIES_FETCH_SUCCESS';
export const COUNTRIES_FETCH_FAIL = 'COUNTRIES_FETCH_FAIL';
export const COUNTRIES_FETCH_END = 'COUNTRIES_FETCH_END';
export const COUNTRIES_INDICATOR_LOADED = 'COUNTRIES_INDICATOR_LOADED';

export const DATA_FETCH_START = 'DATA_FETCH_START';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAIL = 'DATA_FETCH_FAIL';
export const DATA_FETCH_END = 'DATA_FETCH_END';
export const DATA_CALLS_INC = 'DATA_CALLS_INC';
export const WORLD_INDICATOR_LOADED = 'WORLD_INDICATOR_LOADED';

export const FILTER_SELECTION_ADD = 'FILTER_SELECTION_ADD';
export const FILTER_SELECTION_REMOVE = 'FILTER_SELECTION_REMOVE';
export const FILTER_SELECTION_CLEAR_ALL = 'FILTER_SELECTION_CLEAR_ALL';
export const FILTER_SELECT_YEARS = 'FILTER_SELECT_YEARS';
